### ISSUE TITLE
Additional questions on QoD APIs

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/rep_main#18]
Questions/Comments are from Telefonica @jordonezlucena 

1.  In v2, there is no PATCH operation nor ‘sessionUpdate’ schema. These two artifacts were present in v1, but have been removed in rev2. What is the reason for this removal? How the API consumer can then change QoS over a running session?
2.  I suggest merging “qos-throughput” and “qos-stable-latency” API’s into a single “qos” APIs. The structure is quite similar – the only difference is a couple of data schemas.
3.  We should agree on what ‘Throughput_S/M/L’ and ‘LOW_LATENCY’ mean, and document their mapping to standard 3GPP QCI/5QI values. This is quite important to 1) guarantee replicability and reproducibility of results when testing solution in two different telco networks; 2) ensure 3rd party has a clear understanding of what every tag means.

**Comment by shilpa-padgaonkar** [comment]
@jordonezlucena: Here are some intial comments which we can discuss in detail in the WG call on 10th Dec

1. The create operation in the first version had the possibility to create a session without any qos requirements and then patch was to specify this later. It was not to change from an existing qos one to another. To change the qos, consumer currently has to delete existing one and create a new one. We also learned during vendor integration, that not all operations of the NEF QoS API were supported - PATCH was one of them. This might be similar in other vendor NEF solutions. So the API somehow reflects the minimum set of API operations required to CREATE and DELETE a QoS Session. We could of-course "mimic" a PATCH operation on SENF-level and translate it to CREATE/DELETE operations on NEF level, if needed - but that creates more complexity in the SENF implementation.IF we later introduce this possibility, patch can be brought in again. For now we have kept it simple

2. Currently they are quite similar and yes could have been merged into one. However we expect some changes in the 2 specs going ahead so have kept them as separate apis. Also this decision was more influenced by the product team. 

3.  Agree

**Comment by jordonezlucena** [comment]
Agree with 1 and 2. For 3, should we take the decision on this issue before closing it?

**Comment by shilpa-padgaonkar** [comment]
Description specified here:-
(3)We should agree on what ‘Throughput_S/M/L’ and ‘LOW_LATENCY’ mean, and document their mapping to standard 3GPP QCI/5QI values. This is quite important to 1) guarantee replicability and reproducibility of results when testing solution in two different telco networks; 2) ensure 3rd party has a clear understanding of what every tag means.

added to issue 21 for more clarity. Closing this issue
