### ISSUE TITLE
Alliance name - collect proposals

### ISSUE THREAD

**Issue by piwesol** [camaraproject/rep_main#8]
We propose two step approach. First collect name proposals (this issue). Second create a poll and vote. Please add your name and discuss. 

Initial proposals as discussed before - at least two votes in last voting.

| Name | Description | Who proposed |
| --- | ---| --- |
| Telco Global API Alliance | Working name | 
| NEXO | Acronym for “Network EXposure OpenAPIs alliance” | Telefonica |
| Camara | Greek word for "arched roof“, which represents the collaboration or alliance of several entities under one vision. The logo could be an arch or an arched roof | Deutsche Telekom |
| NetworkAPI | Descriptive name to allow developers to find and associate quickly | Deutsche Telekom |

**Comment by MarkusKuemmerle** [comment]
Changed name to CAMARA 27.11.2021 6pm CET
